# Generated by Django 2.2 on 2021-01-31 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokeapi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('deffense', models.IntegerField()),
                ('special_deffense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('url_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField()),
                ('evolves_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolves_from', to='pokemon.Pokemon')),
                ('evolves_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolves_to', to='pokemon.Pokemon')),
            ],
        ),
    ]
