# Generated by Django 2.2 on 2021-01-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='width',
            new_name='weight',
        ),
    ]
